# Generated by Django 6.0.1 on 2026-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsignup',
            name='is_unavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealsignup',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mealsignup',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
