# Generated by Django 6.0.1 on 2026-01-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealsignup_is_unavailable_alter_mealsignup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsignup',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
